apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-scrapper-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-scrapper-backend
  template:
    metadata:
      labels:
        app: devops-scrapper-backend
    spec:
      containers:
        - name: backend-container
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/devops-scrapper-backend:${{ github.sha }}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-scrapper-backend
spec:
  selector:
    app: devops-scrapper-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
