apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-scrapper-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-scrapper-frontend
  template:
    metadata:
      labels:
        app: devops-scrapper-frontend
    spec:
      containers:
        - name: frontend-container
          image: techshack176/devops-scrapper-frontend-k8s:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_API_URL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  BACKEND_API_URL: "http://devops-scrapper-backend:8000"

---
apiVersion: v1
kind: Service
metadata:
  name: devops-scrapper-frontend
spec:
  type: LoadBalancer
  selector:
    app: devops-scrapper-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
